sudo: required
dist: trusty
language: node_js
node_js:
- '6.10'

services:
- docker

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- sudo apt-get install -y sshpass

before_script:
- npm install -g @angular/cli

script:
- ng build --prod

after_success:
- if [ $TRAVIS_PULL_REQUEST == "false" ]; then
  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  export REPO=noefc/client
  export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  docker build -f Dockerfile -t $REPO:$COMMIT .
  docker tag $REPO:$COMMIT $REPO:$TAG
  docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  docker push $REPO
  docker build -t noe-fc/client .
  fi

env:
  global:
  - secure: UzfqV/3l2VbJyyJsvMN4yj0rmWBx/JIT0h2x/5Qssg0RtqBJPNGDhIl97eUGi3daOWkgknSQ/apqUJleLysUfutr1sgM4DWEn+CkELxHzD5RFMVAsuULxuCAzgmWC5Kumc94UGgY/yBBHg9AdPllASyM6gZkJvWA/ONk0meRTldd9w5U3H+e2cmDEgiPZeqWTkJbgMto8BhtZncqm2dp0qYs/BSZJ9IIRqVrQ1IJxhBq6YQSMlD5ZU1p6dL8O9+rc/VYJmvOP/hvWcw1GlMmFNS4078+CH7vCX32Fok5siqgag0UbiTO7QkIn64/kMhKaTv47cU5kyMux3HMRqyjpTI5umSLH+0MtbGxUqaz5ZENd1rG31zGP/4pcbyXFFR79hcR6N58cCscfLHL0CtB9PEFRiWB0DS1bLOi6OXdGnub735B3nroJ8Q51W+OW/vQWGoL5cKKO7YsorgQ+BRDIuup5wogbjbyttTQ2QkZ/2JurK7Rmm07Adc4/27OjDbTiOQEEiR7wVHEitrXAefAUBjtumjDev4BaKqfNsG5Pep6b+4aXZ5nH0gY0ayTF0HlqkLAWEDTfSU7Cm8UJp8JIXpMS+s62m27vKTHmuFIv9qDH+7nvbi5S9zRqFgAAkeYZc0GdvoWok+CmjJ+dF7J048nc2SsSa0fxRwtd6pTeCQ= #DOCKER_EMAIL
  - secure: ez/PuK7oMqryd3g7BEPd32uGwEKtICi39HDPCCMPCyLZeWw6iux1JX3kA7BdqXirypC6mK1zX/ln5dzRV/Uon/DXJmjNCFlMj9HmIrQLKsETTAQ8+o6KWJkSZE/Qtz6c8PIDdS51+OR8rfoUjTRdDrUFToqPPlJWxvHRIEZxUUuhp6KZLzyLN1/ReP+6MSlSFrhHDoCdrm96m6eU2FtOkn/Hpo/BfBm5PKjtGcp3ZhVIhBTFzWEPH7+TrhnsNs1LEAFV3ADV9VFLSLNcUYb1zDGYzWIw2biu3DiqMqe5rgIkm4TjXULrp6XXWb20f1GNoHRZ4kxeaw4VdisiiGBuq0MqdUqiJnDdoscLw4bWNDRaE1hYy3Qc+WwDwou0Ua0RUl33r3c52r7sJYgpXVrXNs+fz/j6DVqvB1DVu0kyKTSfC8kliTkO5boPZyTXKTpv05eSkgIVqiUiNYY4xdd1SdmkzLGIn6K6qhYule1WcEK5ho4Dc9ZnMUzTmmCGLKkctqkjBmS69aZ8tcbSXF6U4HinbEFbp8Hs1MseWQdUcUD60+GBPxKIXrb74t0/f5FNHAK6CMZn0YbfDl89m3P6DH6tfpK1XHh/UB2AxEgl9KsfH0sdOi9maCpy+HWLjN/q+u8tW66EpZHWe3dPu4r8ebxQCaDFGoAaaZuoQXwVK50= #DOCKER_USER
  - secure: AvGQ4cQ9/nqQAaOW2H5Hg4yiZnAZbBqaXEqDKtooU3eul6ZYCQFcGqVsqNeCrrqTes1X36oWlPq08XBXbSG1HiUP9VMiS2ShYtkvUpt66XKKFGrGYvSYq7B1/3rZIGEzmzGP+jFOI2qYZGvVGHjRKV0AY6J/rYcngzgkzal2awHpaO+tSXvNKTMz8WKbWWMzVJiiDr0wJJvtW58YB6fKMstJktehq+IzpQS85Fb6OkGpDZnOngTkVuyo1NPgH9GP7M7a8VNE664uoSnGKYcu0PbbGbELruDAEEfedkpc8bpF0Jv71yvAz4evzfHjbe4jgsqQZv2qZoDPGrcxgA6h3GG3QzW+rIhFz5UNdyBWwWqaX/kag0nmiBj8Zg/EHn/prl2d///zl7DQ3QdQEliYPorSnGNARS51Gp4jifm9F6p1XVK3eilSO+huUcLOE7giSrPWBJQ+PEE4qyWbUPHHSvl9neahWyEWcvq6Q/sgkIdjlNbd2Xg53IJCpZHHPk6IYVxsGnCF7r0X49YaJFGuA1oFNNB1RQFJmGqsYmbxQRiDt/y0e9YVOCsbl9ZzW77Bvh1PS+iMFLeBvtgu5+w0mFZ9R3N9X2IvZSVhpyL/D2ogrRGSHKKQKQLxEHeKMTj+tve4cHFk1XGa11MchHYEMBos7aySm6Bemay78tNbsdQ= #DOCKER_PASS
  - COMMIT=${TRAVIS_COMMIT::8}